### ISSUE TITLE
Congrats on first PySimpleGUI....

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dnllln/Hotel-Scheduler#1]
You did some cool stuff for this being your first attempt at a GUI using PySimpleGUI.  It's awesome to be able to give someone a GUI-based tool.... something that looks and acts like software they're used to using.

**Comment by dnllln** [comment]
Hey, I appreciate it and I appreciate your module! It really simplified the process.

I'm currently going through the MIT 6.00.1x course and moving on to reading a few different books on data structures and algorithms before jumping into a web development course, so the project is on hold for now, but I have plans to revisit it in the future and expand it be more modular with PySimpleGUI as it's goto GUI. :)

Thanks again for the amazing tool. I can't wait to see how it expands. It's super intuitive.
